on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  packages: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
      # Publish to NPM
      - uses: actions/checkout@v4
        # Only run if a release was created
        if: ${{ steps.release.outputs.releases_created == 'true' }}
      - uses: actions/setup-node@v4
        with:
          node-version: lts/iron
          #registry-url: 'https://registry.npmjs.org'
          registry-url: 'https://npm.pkg.github.com'
          #scope: '@globus'
          scope: '@project8'
        if: ${{ steps.release.outputs.releases_created == 'true' }}
      - run: npm ci
        if: ${{ steps.release.outputs.releases_created == 'true'  }}
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        if: ${{ steps.release.outputs.releases_created == 'true' }}
